# Generated by Django 4.0.7 on 2022-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('level', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
