name: Django run local version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: Add env
      run: |
        echo "SECRET_KEY=secret-key!" > .env
    - name: Run local version
      env:
        DJANGO_SETTINGS_MODULE: config.settings.local
      run: |
        python manage.py runserver --settings=config.settings.local
